### ISSUE TITLE
pynndescent throws error when n_jobs=-1

### ISSUE THREAD

**Issue by jgraving** [lmcinnes/pynndescent#72] opened 2019-08-31 08:58 UTC
Hi, thanks for your work on this project! Unfortunately I seem to have run into a bug through another project that uses pynndescent as a dependency. The owner suggested that I open an issue here. See here for details:
https://github.com/pavlin-policar/openTSNE/issues/92#issue-487746322

**Comment by lmcinnes** [comment] 2019-09-02 20:12
Thanks. I'll try and get some time soon and see what is causing this -- I was under the impression that we did handle this.

**Comment by lmcinnes** [comment] 2019-09-06 21:25
I did some digging on this, and it looks like an odd error, in that I can't reproduce this with pynndescent directly -- it seems to accept a ``num_jobs=-1`` happily in tests. There may be a deeper issue. In pynndescent we rely on joblib to handle the conversion of ``n_jobs`` to a suitable number via ``effective_n_jobs``. This does depend on the parallel context in use, but it really shouldn't return a negative number, but it seems to have done so and that resulted in the error you got. Cna you provide a little more information, or, at the least a more minimal failure case we can test?

**Comment by jgraving** [comment] 2019-09-07 04:11
Hi, thanks for looking into this. Here is a minimal test case that produces the error with Python 3.7.4 on MacOS 10.14.5 with homebrew/pip installation and Python 3.6.8 on Ubuntu 18.04 with apt/pip installation.

```python
import sys
!{sys.executable} -m pip install -U pynndescent numpy

from pynndescent import NNDescent
import numpy as np

X = np.random.normal(size=(100,10))

nn = NNDescent(X, n_jobs=-1)
```

Ubuntu error:
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-43-21904b375b44> in <module>()
      1 X = np.random.normal(size=(100,10))
      2 
----> 3 nn = NNDescent(X, n_jobs=-1)

/home/jake/.local/lib/python3.6/site-packages/pynndescent/pynndescent_.py in __init__(self, data, metric, metric_kwds, n_neighbors, n_trees, leaf_size, pruning_level, tree_init, random_state, algorithm, max_candidates, n_iters, delta, rho, n_jobs, seed_per_row, verbose)
    552                 verbose=verbose,
    553                 n_jobs=n_jobs,
--> 554                 seed_per_row=seed_per_row,
    555             )
    556         elif algorithm == "standard" or leaf_array.shape[0] == 1:

/home/jake/.local/lib/python3.6/site-packages/pynndescent/threaded.py in nn_descent(data, n_neighbors, rng_state, max_candidates, dist, dist_args, n_iters, delta, rho, rp_tree_init, leaf_array, verbose, n_jobs, seed_per_row)
    583             rng_state,
    584             parallel,
--> 585             seed_per_row=seed_per_row,
    586         )
    587 

/home/jake/.local/lib/python3.6/site-packages/pynndescent/threaded.py in init_current_graph(data, dist, dist_args, n_neighbors, chunk_size, rng_state, parallel, seed_per_row)
    149     # store the updates in an array
    150     max_heap_update_count = chunk_size * n_neighbors * 2
--> 151     heap_updates = np.zeros((n_tasks, max_heap_update_count, 4))
    152     heap_update_counts = np.zeros((n_tasks,), dtype=np.int64)
    153     rng_state_threads = per_thread_rng_state(n_tasks, rng_state)

ValueError: negative dimensions are not allowed
```

Mac Error:
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-bb71e31d135a> in <module>
      7 X = np.random.normal(size=(100,10))
      8 
----> 9 nn = NNDescent(X, n_jobs=-1)

/usr/local/lib/python3.7/site-packages/pynndescent/pynndescent_.py in __init__(self, data, metric, metric_kwds, n_neighbors, n_trees, leaf_size, pruning_level, tree_init, random_state, algorithm, max_candidates, n_iters, delta, rho, n_jobs, seed_per_row, verbose)
    552                 verbose=verbose,
    553                 n_jobs=n_jobs,
--> 554                 seed_per_row=seed_per_row,
    555             )
    556         elif algorithm == "standard" or leaf_array.shape[0] == 1:

/usr/local/lib/python3.7/site-packages/pynndescent/threaded.py in nn_descent(data, n_neighbors, rng_state, max_candidates, dist, dist_args, n_iters, delta, rho, rp_tree_init, leaf_array, verbose, n_jobs, seed_per_row)
    583             rng_state,
    584             parallel,
--> 585             seed_per_row=seed_per_row,
    586         )
    587 

/usr/local/lib/python3.7/site-packages/pynndescent/threaded.py in init_current_graph(data, dist, dist_args, n_neighbors, chunk_size, rng_state, parallel, seed_per_row)
    149     # store the updates in an array
    150     max_heap_update_count = chunk_size * n_neighbors * 2
--> 151     heap_updates = np.zeros((n_tasks, max_heap_update_count, 4))
    152     heap_update_counts = np.zeros((n_tasks,), dtype=np.int64)
    153     rng_state_threads = per_thread_rng_state(n_tasks, rng_state)

ValueError: negative dimensions are not allowed
```

**Comment by lmcinnes** [comment] 2019-09-07 18:18
The actual error here is that ``np.zeros`` is getting instantiated with a size of ``(n_tasks, max_heap_update_count, 4)``, but one (or more) of those dimensions is negative. I believe this is because ``chunk_size``, which is used to set both ``n_tasks`` and ``max_heap_update_count`` is negative. In turn ``chunk_size`` is determined according to a call to ``effective_n_jobs_with_context(n_jobs)``, which is somehow returning a negative number (I think -- I still haven't successfully reproduced the error; I'm working to create a fresh install to test now). So this mostly works correctly, but is not working for you for some reason. I'll get back to you after I've had some attempts at reproducing the error.

**Comment by lmcinnes** [comment] 2019-09-07 18:26
I think I found the reproducibility issue -- the current master doesn't seem to produce the error, but the pip version does. Time to roll out a release to PyPI I guess.

**Comment by lmcinnes** [comment] 2019-09-07 18:35
Okay, it should be fixed now -- it seems the actual problem, oddly enough, was that the README.rst had a formatting issue that prevented PyPI from accepting the upload, so a patched version 0.3.1 never actually made it to PyPI, and this was the source of the problem, which had been fixed for some time, but not actually made available (apparently). Let me know if things work now (assuming some time for the upload of a new version to PyPI to propagate).

**Comment by jgraving** [comment] 2019-09-07 18:49
Wow, what an awful bug! Sorry about that. Seems to be working now. Thanks for tracking it down.

**Comment by lmcinnes** [comment] 2019-09-07 20:19
Glad it is working now. Sorry for not finding the problem sooner, but I'm glad we got there and it turned out to be easy.

**Closed by lmcinnes** 2019-09-07 20:19 UTC
